(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code::Initialization:: *)
(*
PackageVariables.nb: Lists global variables used by the NLinks package.
Copyright (C) 2014 Nelson Rosa Jr.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even the 
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details. You should have 
received a copy of the GNU General Public License along with this program.
If not, see <http://www.gnu.org/licenses/>.
*)


(* ::Input::Initialization:: *)
BeginPackage["RigidBodyDynamics`", "GlobalVariables`"]


(* ::Input::Initialization:: *)
nf::usage = "# of physical constraints";
nv::usage = "# of virutual constraints";
nu::usage = "# of actuators used for virtual constraints";

RBDListConstraints::usage = "";
RBDAddConstraints::usage = "";
RBDRemoveConstraint::usage = "form is {name, expr, n, opts}";
RBDExpandExpression::usage = "";
RBDSetEpsilon::usage = "";

RBDConQ::usage = "";
RBDConV::usage = "";
RBDConA::usage = "";

RBDVirtQ::usage = "";
RBDVirtV::usage = "";
RBDVirtA::usage = "";

RBDTranV::usage = "";

RBDConstraintFunctions::usage = "";

rfun::usage = "";
rdotfun::usage = "";
Tcbfun::usage = "";
Jfun::usage = "";
\[Phi]fun::usage = "";
\[Eta]fun::usage = "";
Kfun::usage = "";



(* ::Input::Initialization:: *)
RBDTree::usage = "";
RBDGetIndex::usage = "";
RBDGetPositionIndex::usage = "";
RBDGetValue::usage = "";


(* ::Input::Initialization:: *)
RBDNewModel::usage = "";
RBDCreateModel::usage = "";
RBDGravity::usage = "";
RBDParameters::usage = "";
RBDJoint::usage = "";
RBDLink::usage = "";
RBDLinks::usage = "";
RBDGetLinkInfo::usage = "";
RBDGetLinkNames::usage = "";
RBDindex::usage = "";
RBDGetDOF::usage = "";


(* ::Input::Initialization:: *)
mm::usage = "# of angular/linear velocities";
nm::usage = "# of spatial velocities";

I3::usage = "";
I6::usage = "";

z1::usage = "";
z3::usage = "";
Z3::usage = "";

z6::usage = "";
Z6::usage = "";

agfun::usage = "";
sfun::usage = "";
XLfun::usage = "";
\[DoubleStruckCapitalI]fun::usage = "";
sdotfun::usage = "";
XL0fun::usage = "";

RBDSpatialFunctions::suage = "";
RBDSpatialPosition::usage = "";

RBDMechanicalQuantities::usage = "returns the kinetic and potential energy, spatial momentum, spatial inertia, mass, position of the center of mass, and the linear velocity of the center of mass of the entire system; vector quantities are in link 0 coordinates.";


(* ::Input::Initialization:: *)
ufun::usage = "";

RBDb::usage = "joint-space internal forces; Coriolis, centrifugal, and gravitational forces";
RBDM::usage = "joint-space inertia tensor";

RBDqdd::usage = "joint-space accelerations";
RBDJ::usage = "operation space Jacobian matrix";

RBDEOM::usage = "equations of motion";
RBDIME::usage = "impulse-momentum equation";

RBDMQ::usage = "mechanical quantities";


(* ::Input::Initialization:: *)
RBDCompileExpression::usage = "";
RBDCompileFunction::usage = "";
RBDSaveDynamics::usage = "";
(*RBDDeleteDynamics::usage = "";*)
RBDLoadDynamics::usage = "";


(* ::Input::Initialization:: *)
RBDMergeRecipes::usage = "";
RBDGetRecipe::usage = "";


(* ::Input::Initialization:: *)
Begin["`Private`"]

mm = 3;
nm = 6;

I3 = IdentityMatrix@mm;
I6 = IdentityMatrix@nm;

z1 = 0; (* LTDL *)
z3 = Table[0, mm];
Z3 = Table[0, mm, mm];

z6 = Table[0, nm];
Z6 = Table[0, nm, nm];


(* ::Input::Initialization:: *)
End[]
EndPackage[]
