(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["BipedalLocomotion`"]

BLbiped::usage = "";
BLn::usage = "# of continuation parameters; must be <= nc";


(* ::Input::Initialization:: *)
NumberOfCoefficients::usage = "";
PolynomialCoeffcients::usage = "";
PolynomialPlot::usage = "";
PolynomialTrajectory::usage = "";


(* ::Input::Initialization:: *)
BLMap::usage = "";
BLP::usage ="";
BL\[Eta]p::usage = "";

BLc::usage = "";
BLc0T::usage = "";
BLmxc0::usage = "continuation parameters to post-impact parameters, 0+";
BLmxcp::usage = "continuation parameters to pre-impact parameters, 0-";


(* ::Input::Initialization:: *)
BLTangentSpace::usage = "";
BLGenerateGaits::usage = "";
BLGlobalHomotopy::usage = "";


(* ::Input::Initialization:: *)
BLWidth::usage = "";
BLRadius::usage = "";
BLAxes::usage = "";
BLLinkColor::usage = "";
BLJointColor::usage = "";
BLDontDraw::usage  = "";
BLDrawBiped::usage  = "";
BLDrawAxes::usage = "";
BLSim::usage = "";
BLAnimateBiped::usage  = "";
BLScaleLengths::usage = "";
BLBipedGrid::usage = "";
BLWalkingSurface::usage = "";
BLLaTex::usage = "LaTex/IEEETrans text width, column width, and image height values.";
BLPlotProjection::usage = "";
BLBoundingBox::usage = "";
BLBipedTimeGrid::usage = "";
BLManifold::usage = "";
BLFramePlot::usage= "";
BLSingularPointQ::usage = "";
BLWrap::usage = "";
BLDrawCOM::usage = "";
BLAddPOI::usage = "";
BLDrawJoints::usage = "";
BLSimGaitKinematics::usage = "";
BLGaitKinematics::usage = "";
BLBipedFFMPEG::usage = "";
BLFormatPlot::usage = "";
BLTeX::usage = "";
BLPath::usage = "";
BLExportTo::usage = "";
BLImportFrom::usage = "";
BLSaveTo::usage = "";
BLGetFrom::usage = "";


(* ::Input::Initialization:: *)
BLCreateBipedToThreeJS::usage = "";
BLExportBipedToThreeJS::usage = "";
BLMeshOptions::usage = "";


(* ::Input::Initialization:: *)
BLIndicatorFunction::usage = "";
BLIndicatorFunctionPlot::usage = "";
BLFindBifurcation::usage = "";
BLIndicatorFunctionQ::usage = "";


(* ::Input::Initialization:: *)
Begin["`Private`"]

BLbiped = <||>;


(* ::Input::Initialization:: *)
End[]
EndPackage[]
