(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["BipedalLocomotion`Model`"]


(* ::Input::Initialization:: *)
BLAngle::usage ="";
BLState::usage = "";
BLFeet::usage = "";
BLGetFootFalls::usage = "";
BLLinks::usage = "";
BLValues::usage = "";
BLIndices::usage = "";
BLSetAngles::usage = "";
BLGetBipedBase::usage = "";
BLJacobian::usage = "";
BLEigenvalues::usage = "";
BLWalk::usage = "";
BL\[Sigma]::usage = "";
BLSide::usage = "";


(* ::Input::Initialization:: *)
BLA::usage = "";

BLTimeBasedceq::usage ="";
BLTimeBasedContinuationParameters::usage = "";

BLContinuationIndices::usage = "";

BLCreateContinuationParameters::usage = "";

BLGetIndex::usage = "";
BLGetValue::usage = "";

BLContinuationParameters::usage = "";

BLSummary::usage = "";

BLGetSwitchingTimes::usage = "";

BLLinearizedDynamics::usage = "";


(* ::Input::Initialization:: *)
BLCreateBiped::usage = "";
BLRegime::usage = "";
BLConstraints::usage = "";
BLxT::usage = "";


(* ::Input::Initialization:: *)
BLCompileBiped::usage = "";
BLConstraintFunctions::usage = "";

Pfun::usage = "";
B0fun::usage = "";
BTfun::usage = "";

BLF::usage = "";
BLH::usage = "";


(* ::Input::Initialization:: *)



(* ::Input::Initialization:: *)
Begin["`Private`"]

angles = {};
angs = {};

(* primarily used in Compile *)
fcon = <||>;

(* primarily used in Recipes and Compile *)
con = <||>;


(* ::Input::Initialization:: *)
End[]
EndPackage[]
