on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Release Version
        run: |
            echo "ver=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
            echo "name=${GITHUB_REPOSITORY#nr-codes/}" >> $GITHUB_ENV
      - name: Build Mathematica Archive
        id: math
        env: 
            math: ${{ env.name }}-Mathematica-${{ env.ver }}
        run: |
            sudo apt-get install w3m
            npx asciidoctor -a html_compact -a revnumber=v$ver README.adoc
            w3m -dump -o display_charset=latin1 README.html > README.txt
            echo "The content in this directory contains a video showing " \
                 "animations of all gaits presented in the figures of the " \
                 "paper as well as the source code for computing walking " \
                 "gaits from equilibria using numerical continuation " \
                 "methods.  Further information can be found in the " \
                 "README.txt file." > SUMMARY.txt 
            zip -9 $math \
                README.txt \
                SUMMARY.txt \
                COPYING.txt \
                Installer.nb \
                RunModels.nb \
                BipedalGaitGeneration.mp4 \
                Figures \
                Models \
                SIMple \
                Misc/DebuggingTips.pdf \
                GaitBrowser/src/bipeds \
                GaitBrowser/app/imgs/*/*.png \
                -x \*.gitignore
            zip -r9 $math Models SIMple
            echo "math=$math.zip" >> $GITHUB_ENV
            echo "math_path=$( readlink -f $math )" >> $GITHUB_ENV
      - name: Build Node.js Archive
        id: node
        env: 
            node: ${{ env.name }}-Node.js-${{ env.ver }}
        run: |
            zip -r9 $node GaitBrowser -x GaitBrowser/app/imgs\*
            echo "node=$node.zip" >> $GITHUB_ENV
            echo "node_path=$( readlink -f $node )" >> $GITHUB_ENV
      - name: Build GaitBrowser Executables
        id: executables
        env: 
            lin: GaitBrowser-linux-x64-${{ env.ver }}
            mac: GaitBrowser-macos-x64-${{ env.ver }}
            win: GaitBrowser-win-x64-${{ env.ver }}.exe
        run: |
            cd ./GaitBrowser
            npm i
            npm run build
            npm run pkg-all
            echo "lin=$lin" >> $GITHUB_ENV
            echo "mac=$mac" >> $GITHUB_ENV
            echo "win=$win" >> $GITHUB_ENV
            echo "lin_path=$( readlink -f ./exe/GaitBrowser-linux )" >> $GITHUB_ENV
            echo "mac_path=$( readlink -f ./exe/GaitBrowser-macos )" >> $GITHUB_ENV
            echo "win_path=$( readlink -f ./exe/GaitBrowser-win.exe )" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Mathematica Archive
        id: upload-math-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ env.math_path }}
          asset_name: ${{ env.math }}
          asset_content_type: application/zip
      - name: Upload Node.js Archive
        id: upload-node-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ env.node_path }}
          asset_name: ${{ env.node }}
          asset_content_type: application/zip
      - name: Upload GaitBrowser Linux Executable
        id: upload-linux-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ env.lin_path }}
          asset_name: ${{ env.lin }}
          asset_content_type: application/octet-stream
      - name: Upload GaitBrowser MacOS Executable
        id: upload-macos-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ env.mac_path }}
          asset_name: ${{ env.mac }}
          asset_content_type: application/octet-stream
      - name: Upload GaitBrowser Windows Executable
        id: upload-win-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ env.win_path }}
          asset_name: ${{ env.win }}
          asset_content_type: application/octet-stream
